from tkinter import *
import random
import time

# Initialize canvas
CANVAS_WIDTH = 500
CANVAS_HEIGHT = 500

tk = Tk()
canvas = Canvas(tk, width=CANVAS_WIDTH, height=CANVAS_HEIGHT)
tk.title("King")
canvas.pack()

# Initialize images
IMAGE_WIDTH = 100
IMAGE_OFFSET_X = (CANVAS_WIDTH - IMAGE_WIDTH) / 2
IMAGE_OFFSET_Y = 120

# Crown
CROWN_HIGH_POINT = IMAGE_OFFSET_Y + 0
CROWN_MID_POINT = IMAGE_OFFSET_Y + 20
CROWN_LOW_POINT = IMAGE_OFFSET_Y + 30
CROWN_HEIGHT = IMAGE_OFFSET_Y + 60
CROWN_SUB_WIDTH = IMAGE_WIDTH / 5

canvas.create_polygon(
    IMAGE_OFFSET_X + CROWN_SUB_WIDTH * 0, CROWN_MID_POINT,
    IMAGE_OFFSET_X + CROWN_SUB_WIDTH * 1, CROWN_LOW_POINT,
    IMAGE_OFFSET_X + CROWN_SUB_WIDTH * 2, CROWN_HIGH_POINT,
    IMAGE_OFFSET_X + CROWN_SUB_WIDTH * 3, CROWN_LOW_POINT,
    IMAGE_OFFSET_X + CROWN_SUB_WIDTH * 4, CROWN_MID_POINT,
    IMAGE_OFFSET_X + CROWN_SUB_WIDTH * 4, CROWN_HEIGHT,
    IMAGE_OFFSET_X + CROWN_SUB_WIDTH * 0, CROWN_HEIGHT,
    IMAGE_OFFSET_X + CROWN_SUB_WIDTH * 0, CROWN_MID_POINT,
    fill="gold",
    tags="crown"
)

# Beard
BEARD_POS_X = IMAGE_OFFSET_X + 0
BEARD_POS_Y = IMAGE_OFFSET_Y + 100
BEARD_LENGTH = 100
BEARD_SPACE = CROWN_SUB_WIDTH * 5 / 6

canvas.create_line(BEARD_POS_X + BEARD_SPACE * 0, BEARD_POS_Y, BEARD_POS_X + BEARD_SPACE * 0, BEARD_POS_Y + BEARD_LENGTH, tags="beard_1")
canvas.create_line(BEARD_POS_X + BEARD_SPACE * 1, BEARD_POS_Y, BEARD_POS_X + BEARD_SPACE * 1, BEARD_POS_Y + BEARD_LENGTH, tags="beard_2")
canvas.create_line(BEARD_POS_X + BEARD_SPACE * 2, BEARD_POS_Y, BEARD_POS_X + BEARD_SPACE * 2, BEARD_POS_Y + BEARD_LENGTH, tags="beard_3")
canvas.create_line(BEARD_POS_X + BEARD_SPACE * 3, BEARD_POS_Y, BEARD_POS_X + BEARD_SPACE * 3, BEARD_POS_Y + BEARD_LENGTH, tags="beard_4")
canvas.create_line(BEARD_POS_X + BEARD_SPACE * 4, BEARD_POS_Y, BEARD_POS_X + BEARD_SPACE * 4, BEARD_POS_Y + BEARD_LENGTH, tags="beard_5")
canvas.create_line(BEARD_POS_X + BEARD_SPACE * 5, BEARD_POS_Y, BEARD_POS_X + BEARD_SPACE * 5, BEARD_POS_Y + BEARD_LENGTH, tags="beard_6")

# Base
BASE_SPACE_Y = CROWN_SUB_WIDTH
BASE_POS_X = BEARD_POS_X
BASE_POS_Y = BEARD_POS_Y + BEARD_LENGTH + BASE_SPACE_Y
BASE_WIDTH = CROWN_SUB_WIDTH * 4.1

canvas.create_line(BASE_POS_X, BASE_POS_Y, BASE_POS_X + BASE_WIDTH, BASE_POS_Y, tags="base")

# Feet
LEG_LENGTH = 30
LEG_GAP = CROWN_SUB_WIDTH * 2
FOOT_COLOR = "grey"
FOOT_SPACE_Y = 0
FOOT_WIDTH = CROWN_SUB_WIDTH * 1.5
FOOT_HEIGHT = CROWN_SUB_WIDTH * 2/3

LEFT_FOOT_POS_X = IMAGE_OFFSET_X - (CROWN_SUB_WIDTH / 2)
LEFT_FOOT_POS_Y = BASE_POS_Y + FOOT_SPACE_Y + LEG_LENGTH
LEFT_LEG_POS_X = LEFT_FOOT_POS_X + FOOT_WIDTH
LEFT_LEG_POS_Y = LEFT_FOOT_POS_Y + (FOOT_HEIGHT / 2)

RIGHT_FOOT_POS_X = LEFT_LEG_POS_X + LEG_GAP
RIGHT_FOOT_POS_Y = LEFT_FOOT_POS_Y
RIGHT_LEG_POS_X = RIGHT_FOOT_POS_X
RIGHT_LEG_POS_Y = RIGHT_FOOT_POS_Y + (FOOT_HEIGHT / 2)

canvas.create_line(LEFT_LEG_POS_X, LEFT_LEG_POS_Y, LEFT_FOOT_POS_X + FOOT_WIDTH, LEFT_FOOT_POS_Y + FOOT_HEIGHT - LEG_LENGTH, tags="left_foot")
canvas.create_oval(LEFT_FOOT_POS_X, LEFT_FOOT_POS_Y, LEFT_FOOT_POS_X + FOOT_WIDTH, LEFT_FOOT_POS_Y + FOOT_HEIGHT, tags="left_foot", fill=FOOT_COLOR)

canvas.create_line(RIGHT_LEG_POS_X, RIGHT_LEG_POS_Y, RIGHT_FOOT_POS_X, RIGHT_FOOT_POS_Y + FOOT_HEIGHT - LEG_LENGTH, tags="right_foot")
canvas.create_oval(RIGHT_FOOT_POS_X, RIGHT_FOOT_POS_Y, RIGHT_FOOT_POS_X + FOOT_WIDTH, RIGHT_FOOT_POS_Y + FOOT_HEIGHT, tags="right_foot", fill=FOOT_COLOR)

tk.mainloop()